#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/delay.h>
#include <linux/fb.h>
#include <linux/display-sys.h>
#include <linux/rk_screen.h>
#include <linux/rk_fb.h>
#ifdef CONFIG_OF
#include <linux/of.h>
#include <linux/of_gpio.h>
#endif

#include "../../edid.h"

#ifdef CONFIG_SWITCH
#include <linux/switch.h>
#endif
	
#define DDC_ADDR		0x50
#define DDC_I2C_RATE		100*1000
#define INVALID_GPIO		-1
#define GPIO_HIGH		1
#define GPIO_LOW		0
#define DISPLAY_SOURCE_LCDC0    0
#define DISPLAY_SOURCE_LCDC1    1

struct rockchip_vga {
	struct device 		 *dev;	/*i2c device*/
	struct rk_display_device *ddev; /*display device*/
	struct i2c_client 	 *client;
	struct list_head	 modelist;
	struct fb_monspecs	 specs;
	struct rk_screen	 screen;
	int 			 indx;
	int 			 en_pin;
	int 			 en_val;
	int 			 lcdc_id;
#ifdef CONFIG_SWITCH
	struct switch_dev	 switch_vga;
#endif
};

#define VIDEO_MODE(nm, c, hd, vd, rm, lm, lom, um, hl, vl, sc, vf) \
	.name = nm, .pixclock = (c), .xres = (hd), .yres = (vd), \
	.right_margin = (rm), .left_margin = (lm), \
	.lower_margin = (lom), .upper_margin = (um), \
	.hsync_len = (hl), .vsync_len = (vl),  \
	.sync = (sc), .refresh = (vf), .vmode = FB_VMODE_NONINTERLACED

/*
 * Autogenerated from the DMT spec.
 * This table is copied from drivers/gpu/drm/drm_edid.c
 */
static const struct fb_videomode video_dmt_modes[] = {
	/* 640x350@85Hz */
	{ VIDEO_MODE("640x350", KHZ2PICOS(31500), 640, 350, 32, 96, 32,
	 60, 64, 3, FB_SYNC_HOR_HIGH_ACT, 85) },
	/* 640x400@85Hz */
	{ VIDEO_MODE("640x400", KHZ2PICOS(31500), 640, 400, 32, 96, 1,
	 41, 64, 3, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 720x400@85Hz */
	{ VIDEO_MODE("720x400", KHZ2PICOS(35500), 720, 400, 36, 108, 1,
	 42, 72, 3, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 640x480@60Hz */
	{ VIDEO_MODE("640x480", KHZ2PICOS(25175), 640, 480, 16, 48, 9,
	 33, 96, 3, 0, 60) },
	/* 640x480@72Hz */
	{ VIDEO_MODE("640x480", KHZ2PICOS(31500), 640, 480, 24, 128, 9,
	 28, 40, 3, 0, 72) },
	/* 640x480@75Hz */
	{ VIDEO_MODE("640x480", KHZ2PICOS(31500), 640, 480, 16, 120, 1,
	 16, 64, 3, 0, 75) },
	/* 640x480@85Hz */
	{ VIDEO_MODE("640x480", KHZ2PICOS(36000), 640, 480, 56, 80, 1,
	 25, 56, 3, 0, 85) },
	/* 800x600@56Hz */
	{ VIDEO_MODE("800x600", KHZ2PICOS(36000), 800, 600, 24, 128, 1,
	 22, 72, 2, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 56) },
	/* 800x600@60Hz */
	{ VIDEO_MODE("800x600", KHZ2PICOS(40000), 800, 600, 40, 88, 1,
	 23, 128, 4, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 800x600@72Hz */
	{ VIDEO_MODE("800x600", KHZ2PICOS(50000), 800, 600, 56, 64, 37,
	 23, 120, 6, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 72) },
	/* 800x600@75Hz */
	{ VIDEO_MODE("800x600", KHZ2PICOS(49500), 800, 600, 16, 160, 1,
	 21, 80, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 800x600@85Hz */
	{ VIDEO_MODE("800x600", KHZ2PICOS(56250), 800, 600, 32, 152, 1,
	 27, 64, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 800x600@120Hz RB */
	{ VIDEO_MODE("800x600", KHZ2PICOS(73250), 800, 600, 48, 80, 3,
	 29, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 848x480@60Hz */
	{ VIDEO_MODE("848x480", KHZ2PICOS(33750), 848, 480, 16, 112, 6,
	 23, 112, 8, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1024x768@60Hz */
	{ VIDEO_MODE("1024x768", KHZ2PICOS(65000), 1024, 768, 24, 160, 3,
	 29, 136, 6, 0, 60) },
	/* 1024x768@70Hz */
	{ VIDEO_MODE("1024x768", KHZ2PICOS(75000), 1024, 768, 24, 144, 3,
	 29, 136, 6, 0, 70) },
	/* 1024x768@75Hz */
	{ VIDEO_MODE("1024x768", KHZ2PICOS(78750), 1024, 768, 16, 176, 1,
	 28, 96, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1024x768@85Hz */
	{ VIDEO_MODE("1024x768", KHZ2PICOS(94500), 1024, 768, 48, 208, 1,
	 36, 96, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1024x768@120Hz RB */
	{ VIDEO_MODE("1024x768", KHZ2PICOS(115500), 1024, 768, 48, 80, 3,
	 38, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1152x864@75Hz */
	{ VIDEO_MODE("1152x864", KHZ2PICOS(108000), 1152, 864, 64, 256, 1,
	 32, 128, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1280x768@60Hz RB */
	{ VIDEO_MODE("1280x768", KHZ2PICOS(68250), 1280, 768, 48, 80, 3,
	 12, 32, 7, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1280x768@60Hz */
	{ VIDEO_MODE("1280x768", KHZ2PICOS(79500), 1280, 768, 64, 192, 3,
	 20, 128, 7, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1280x768@75Hz */
	{ VIDEO_MODE("1280x768", KHZ2PICOS(102250), 1280, 768, 80, 208, 3,
	 27, 128, 7, FB_SYNC_HOR_HIGH_ACT, 75) },
	/* 1280x768@85Hz */
	{ VIDEO_MODE("1280x768", KHZ2PICOS(117500), 1280, 768, 80, 216, 3,
	 31, 136, 7, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1280x768@120Hz RB */
	{ VIDEO_MODE("1280x768", KHZ2PICOS(140250), 1280, 768, 48, 80, 3,
	 35, 32, 7, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1280x800@60Hz RB */
	{ VIDEO_MODE("1280x800", KHZ2PICOS(71000), 1280, 800, 48, 80, 3,
	 14, 32, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1280x800@60Hz */
	{ VIDEO_MODE("1280x800", KHZ2PICOS(83500), 1280, 800, 72, 200, 3,
	 22, 128, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1280x800@75Hz */
	{ VIDEO_MODE("1280x800", KHZ2PICOS(106500), 1280, 800, 80, 208, 3,
	 29, 128, 6, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1280x800@85Hz */
	{ VIDEO_MODE("1280x800", KHZ2PICOS(122500), 1280, 800, 80, 216, 3,
	 34, 136, 6, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1280x800@120Hz RB */
	{ VIDEO_MODE("1280x800", KHZ2PICOS(146250), 1280, 800, 48, 80, 3,
	 38, 32, 6, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1280x960@60Hz */
	{ VIDEO_MODE("1280x960", KHZ2PICOS(108000), 1280, 960, 96, 312, 1,
	 36, 112, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1280x960@85Hz */
	{ VIDEO_MODE("1280x960", KHZ2PICOS(148500), 1280, 960, 64, 224, 1,
	 47, 160, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1280x960@120Hz RB */
	{ VIDEO_MODE("1280x960", KHZ2PICOS(175500), 1280, 960, 48, 80, 3,
	 50, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1280x1024@60Hz */
	{ VIDEO_MODE("1280x1024", KHZ2PICOS(108000), 1280, 1024, 48, 248, 1,
	 38, 112, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1280x1024@75Hz */
	{ VIDEO_MODE("1280x1024", KHZ2PICOS(135000), 1280, 1024, 16, 248, 1,
	 38, 144, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1280x1024@85Hz */
	{ VIDEO_MODE("1280x1024", KHZ2PICOS(157500), 1280, 1024, 64, 224, 1,
	 44, 160, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1280x1024@120Hz RB */
	{ VIDEO_MODE("1280x1024", KHZ2PICOS(187250), 1280, 1024, 48, 80, 3,
	 50, 32, 7, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1360x768@60Hz */
	{ VIDEO_MODE("1360x768", KHZ2PICOS(85500), 1360, 768, 64, 256, 3,
	 18, 112, 6, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1360x768@120Hz RB */
	{ VIDEO_MODE("1360x768", KHZ2PICOS(148250), 1360, 768, 48, 80, 3,
	 37, 32, 5, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1400x1050@60Hz RB */
	{ VIDEO_MODE("1400x1050", KHZ2PICOS(101000), 1400, 1050, 48, 80, 3,
	 23, 32, 4, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1400x1050@60Hz */
	{ VIDEO_MODE("1400x1050", KHZ2PICOS(121750), 1400, 1050, 88, 232, 3,
	 32, 144, 4, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1400x1050@75Hz */
	{ VIDEO_MODE("1400x1050", KHZ2PICOS(156000), 1400, 1050, 104, 248, 3,
	 42, 144, 4, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1400x1050@85Hz */
	{ VIDEO_MODE("1400x1050", KHZ2PICOS(179500), 1400, 1050, 104, 256, 3,
	 48, 152, 4, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1400x1050@120Hz RB */
	{ VIDEO_MODE("1400x1050", KHZ2PICOS(208000), 1400, 1050, 48, 80, 3,
	 55, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1440x900@60Hz RB */
	{ VIDEO_MODE("1440x900", KHZ2PICOS(88750), 1440, 900, 48, 80, 3,
	 17, 32, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1440x900@60Hz */
	{ VIDEO_MODE("1440x900", KHZ2PICOS(106500), 1440, 900, 80, 232, 3,
	 25, 152, 6, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1440x900@75Hz */
	{ VIDEO_MODE("1440x900", KHZ2PICOS(136750), 1440, 900, 96, 248, 3,
	 33, 152, 6, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1440x900@85Hz */
	{ VIDEO_MODE("1440x900", KHZ2PICOS(157000), 1440, 900, 104, 256, 3,
	 39, 152, 6, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1440x900@120Hz RB */
	{ VIDEO_MODE("1440x900", KHZ2PICOS(182750), 1440, 900, 48, 80, 3,
	 44, 32, 6, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1600x1200@60Hz */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(162000), 1600, 1200, 64, 304, 1,
	 46, 192, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1600x1200@65Hz */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(175500), 1600, 1200, 64, 304, 1,
	 46, 192, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 65) },
	/* 1600x1200@70Hz */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(189000), 1600, 1200, 64, 304, 1,
	 46, 192, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 70) },
	/* 1600x1200@75Hz */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(202500), 1600, 1200, 64, 304, 1,
	 46, 192, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1600x1200@85Hz */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(229500), 1600, 1200, 64, 304, 1,
	 46, 192, 3, FB_SYNC_HOR_HIGH_ACT | FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1600x1200@120Hz RB */
	{ VIDEO_MODE("1600x1200", KHZ2PICOS(268250), 1600, 1200, 48, 80, 3,
	 64, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1680x1050@60Hz RB */
	{ VIDEO_MODE("1680x1050", KHZ2PICOS(119000), 1680, 1050, 48, 80, 3,
	 21, 32, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1680x1050@60Hz */
	{ VIDEO_MODE("1680x1050", KHZ2PICOS(146250), 1680, 1050, 104, 280, 3,
	 30, 176, 6, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1680x1050@75Hz */
	{ VIDEO_MODE("1680x1050", KHZ2PICOS(187000), 1680, 1050, 120, 296, 3,
	 40, 176, 6, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1680x1050@85Hz */
	{ VIDEO_MODE("1680x1050", KHZ2PICOS(214750), 1680, 1050, 128, 304, 3,
	 46, 176, 6, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1680x1050@120Hz RB */
	{ VIDEO_MODE("1680x1050", KHZ2PICOS(245500), 1680, 1050, 48, 80, 3,
	 53, 32, 6, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1792x1344@60Hz */
	{ VIDEO_MODE("1792x1344", KHZ2PICOS(204750), 1792, 1344, 128, 328, 1,
	 46, 200, 3, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1792x1344@75Hz */
	{ VIDEO_MODE("1792x1344", KHZ2PICOS(261000), 1792, 1344, 96, 352, 1,
	 69, 216, 3, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1792x1344@120Hz RB */
	{ VIDEO_MODE("1792x1344", KHZ2PICOS(333250), 1792, 1344, 48, 80, 3,
	 72, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1856x1392@60Hz */
	{ VIDEO_MODE("1856x1392", KHZ2PICOS(218250), 1856, 1392, 96, 352, 1,
	 43, 224, 3, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1856x1392@75Hz */
	{ VIDEO_MODE("1856x1392", KHZ2PICOS(288000), 1856, 1392, 128, 352, 3,
	 101, 224, 4, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1856x1392@120Hz RB */
	{ VIDEO_MODE("1856x1392", KHZ2PICOS(356500), 1856, 1392, 48, 80, 3,
	 75, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1920x1200@60Hz RB */
	{ VIDEO_MODE("1920x1200", KHZ2PICOS(154000), 1920, 1200, 48, 80, 3,
	 26, 32, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 1920x1200@60Hz */
	{ VIDEO_MODE("1920x1200", KHZ2PICOS(193250), 1920, 1200, 136, 336, 3,
	 36, 200, 6, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1920x1200@75Hz */
	{ VIDEO_MODE("1920x1200", KHZ2PICOS(245250), 1920, 1200, 136, 344, 3,
	 46, 208, 6, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1920x1200@85Hz */
	{ VIDEO_MODE("1920x1200", KHZ2PICOS(281250), 1920, 1200, 144, 352, 3,
	 53, 208, 6, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 1920x1200@120Hz RB */
	{ VIDEO_MODE("1920x1200", KHZ2PICOS(317000), 1920, 1200, 48, 80, 3,
	 62, 32, 6, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 1920x1440@60Hz */
	{ VIDEO_MODE("1920x1440", KHZ2PICOS(234000), 1920, 1440, 128, 344, 1,
	 56, 208, 3, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 1920x1440@75Hz */
	{ VIDEO_MODE("1920x1440", KHZ2PICOS(297000), 1920, 1440, 144, 352, 1,
	 56, 224, 3, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 1920x1440@120Hz RB */
	{ VIDEO_MODE("1920x1440", KHZ2PICOS(380500), 1920, 1440, 48, 80, 3,
	 78, 32, 4, FB_SYNC_HOR_HIGH_ACT, 120) },
	/* 2560x1600@60Hz RB */
	{ VIDEO_MODE("2560x1600", KHZ2PICOS(268500), 2560, 1600, 48, 80, 3,
	 37, 32, 6, FB_SYNC_HOR_HIGH_ACT, 60) },
	/* 2560x1600@60Hz */
	{ VIDEO_MODE("2560x1600", KHZ2PICOS(348500), 2560, 1600, 192, 472, 3,
	 49, 280, 6, FB_SYNC_VERT_HIGH_ACT, 60) },
	/* 2560x1600@75HZ */
	{ VIDEO_MODE("2560x1600", KHZ2PICOS(443250), 2560, 1600, 208, 488, 3,
	 63, 280, 6, FB_SYNC_VERT_HIGH_ACT, 75) },
	/* 2560x1600@85HZ */
	{ VIDEO_MODE("2560x1600", KHZ2PICOS(505250), 2560, 1600, 208, 488, 3,
	 73, 280, 6, FB_SYNC_VERT_HIGH_ACT, 85) },
	/* 2560x1600@120Hz RB */
	{ VIDEO_MODE("2560x1600", KHZ2PICOS(552750), 2560, 1600, 48, 80, 3,
	 85, 32, 6, FB_SYNC_HOR_HIGH_ACT, 120) },
};

static int i2c_master_reg8_recv(const struct i2c_client *client,
		const char reg, char *buf, int count, int scl_rate)
{
        struct i2c_adapter *adap=client->adapter;
        struct i2c_msg msgs[2];
        int ret;
        char reg_buf = reg;

        msgs[0].addr = client->addr;
        msgs[0].flags = client->flags;
        msgs[0].len = 1;
        msgs[0].buf = &reg_buf;
        msgs[0].scl_rate = scl_rate;

        msgs[1].addr = client->addr;
        msgs[1].flags = client->flags | I2C_M_RD;
        msgs[1].len = count;
        msgs[1].buf = (char *)buf;
        msgs[1].scl_rate = scl_rate;

        ret = i2c_transfer(adap, msgs, 2);

        return (ret == 2)? count : ret;
}

static unsigned char *rk29fb_ddc_read(struct i2c_client *client)
{
	int rc;
	unsigned char *buf = kzalloc(EDID_LENGTH, GFP_KERNEL);
	if (!buf) {
		dev_err(&client->dev, "unable to allocate memory for EDID\n");
		return NULL;
	}
	
	/*Check ddc i2c communication is available or not*/
	rc = i2c_master_reg8_recv(client, 0, buf, 6, DDC_I2C_RATE);
	if (rc == 6) {
		memset(buf, 0, EDID_LENGTH);
		rc = i2c_master_reg8_recv(client, 0, buf, EDID_LENGTH, DDC_I2C_RATE);
		if(rc == EDID_LENGTH)
			return buf;
	}

	dev_err(&client->dev, "unable to read EDID block.\n");
	kfree(buf);
	return NULL;
}

static int vga_mode2screen(struct fb_videomode *modedb, struct rk_screen *screen)
{
	if(modedb == NULL || screen == NULL)
		return -1;
		
	memset(screen, 0, sizeof(struct rk_screen));
	memcpy(&screen->mode, modedb, sizeof(*modedb));
	screen->mode.pixclock = PICOS2KHZ(screen->mode.pixclock);
	screen->mode.pixclock /= 250;
	screen->mode.pixclock *= 250;
	screen->mode.pixclock *= 1000;
	screen->xsize = screen->mode.xres;
	screen->ysize = screen->mode.yres;

	screen->overscan.left = 100;
	screen->overscan.top = 100;
	screen->overscan.right = 100;
	screen->overscan.bottom = 100;
	/* screen type & face */
	screen->type = SCREEN_RGB;
	screen->face = OUT_P888;

	screen->pin_vsync = (screen->mode.sync & FB_SYNC_VERT_HIGH_ACT) ? 1 : 0;
	screen->pin_hsync = (screen->mode.sync & FB_SYNC_HOR_HIGH_ACT) ? 1 : 0;
	screen->pin_den = 0;
	screen->pin_dclk = 1;

	/* Swap rule */
	screen->swap_rb = 0;
	screen->swap_rg = 0;
	screen->swap_gb = 0;
	screen->swap_delta = 0;
	screen->swap_dumy = 0;
	/* Operation function*/
	screen->init = NULL;
	screen->standby = NULL;

	return 0;
}

static int vga_switch_screen(struct rockchip_vga *vga)
{
	struct fb_videomode *best_mode;
	struct rk_screen *screen = &vga->screen;
	struct fb_monspecs *specs = &vga->specs;
//	int i;

	/*
	 * best_mode VGA recommend from edid I think is first one.
	 * I guess...
	 */
	best_mode = &specs->modedb[0];
#if 0
	for (i = 0; i < specs->modedb_len; i++) {
		if (best_mode->yres * )
		if ((best_mode->yres * best_mode->xres) <
		    (specs->modedb[i].yres * specs->modedb[i].xres))
			best_mode = &specs->modedb[i];
	}
#endif

	vga_mode2screen(best_mode, screen);

	rk_fb_set_screen(screen);
//	rk_fb_switch_screen(screen, 1 ,vga->lcdc_id);

	return 0;
}

static int vga_get_screen_info(struct rockchip_vga *vga)
{
	u8 *edid;
	int i, j;
	struct fb_monspecs *specs = &vga->specs;
	struct list_head *modelist = &vga->modelist;
	edid = rk29fb_ddc_read(vga->client);
	if (!edid) {
		dev_info(vga->dev, "get edid failed!\n");
		return -EINVAL;
	}
	fb_edid_to_monspecs(edid,specs);
	INIT_LIST_HEAD(modelist);
	for (i = 0; i < specs->modedb_len; i++) {
		/*
		 * we found videomode from edid maybe have some error, so fixed.
		 */
		for (j = 0; j < ARRAY_SIZE(video_dmt_modes); j++) {
			if (specs->modedb[i].xres == video_dmt_modes[j].xres &&
			    specs->modedb[i].yres == video_dmt_modes[j].yres &&
			    specs->modedb[i].pixclock ==
			    video_dmt_modes[j].pixclock)
				memcpy(&specs->modedb[i], &video_dmt_modes[j],
				       sizeof(struct fb_videomode));
		}

		fb_add_videomode(&specs->modedb[i], modelist);

		pr_info("==================\n");
		pr_info("%dx%d@%d-%ld [<:%d >:%d ^:%d v:%d]\n",
			specs->modedb[i].xres, specs->modedb[i].yres,
			specs->modedb[i].refresh,
			(PICOS2KHZ(specs->modedb[i].pixclock)/250)*250*1000,
			specs->modedb[i].left_margin,
			specs->modedb[i].right_margin,
			specs->modedb[i].upper_margin,
			specs->modedb[i].lower_margin);

		pr_info("hpw[%d] vpw[%d] sync[%x vmode%x flag%x \n",
			specs->modedb[i].hsync_len,
			specs->modedb[i].vsync_len,
			specs->modedb[i].sync,
			specs->modedb[i].vmode,
			specs->modedb[i].flag);
	}
	return 0;
	
}

static int vga_get_modelist(struct rk_display_device *device,
			     struct list_head **modelist)
{
	struct rockchip_vga *vga = device->priv_data;
	*modelist = &vga->modelist;
	return 0;
}

static int vga_set_mode(struct rk_display_device *device,
			 struct fb_videomode *mode)
{
	struct rockchip_vga *vga = device->priv_data;
	struct rk_screen *screen = &vga->screen;
	vga_mode2screen(mode, screen);
	rk_fb_switch_screen(screen, 1 ,vga->lcdc_id);

	return 0;
}

static int vga_get_mode(struct rk_display_device *device,
			 struct fb_videomode *mode)
{
	return 0;
}

struct rk_display_ops vga_display_ops = {
	.getmodelist = vga_get_modelist,
	.setmode = vga_set_mode,
	.getmode = vga_get_mode,
};

static int vga_display_probe(struct rk_display_device *device, void *devdata)
{
	device->owner = THIS_MODULE;
	strcpy(device->type, "VGA");
	device->priority = DISPLAY_PRIORITY_VGA;
	device->priv_data = devdata;
	device->ops = &vga_display_ops;
	return 1;
}

static struct rk_display_driver display_vga = {
	.probe = vga_display_probe,
};

struct rk_display_device * vga_register_display_sysfs(struct rockchip_vga *vga)
{
	return rk_display_device_register(&display_vga, vga->dev, vga);
}

void vga_unregister_display_sysfs(struct rockchip_vga *vga)
{
	if (vga->ddev)
		rk_display_device_unregister(vga->ddev);
}

static int vga_i2c_probe(struct i2c_client *client,const struct i2c_device_id *id)
{
	int ret;
	struct rockchip_vga *vga;
	struct device_node *np = client->dev.of_node;
	enum of_gpio_flags pwr_flags;

	if (!np) {
		dev_err(&client->dev, "no device node found!\n");
		return -EINVAL;
	}

	vga = devm_kzalloc(&client->dev, sizeof(*vga), GFP_KERNEL);
	if (!vga) {
		dev_err(&client->dev, "allocate for vga failed!\n");
		return -ENOMEM;
	}

	vga->client = client;
	vga->dev = &client->dev;
	i2c_set_clientdata(client, vga);
	vga->ddev = vga_register_display_sysfs(vga);
	if (IS_ERR(vga->ddev))
		dev_warn(vga->dev, "Unable to create device for vga :%ld",
			PTR_ERR(vga->ddev));
	
	vga->en_pin = of_get_named_gpio_flags(np, "pwr_gpio", 0, &pwr_flags);
	if (gpio_is_valid(vga->en_pin)) {
		vga->en_val = (pwr_flags & OF_GPIO_ACTIVE_LOW) ? 0 : 1;
		ret = devm_gpio_request(vga->dev, vga->en_pin, "pwr_pin");
		if(ret < 0) {
			dev_err(vga->dev, "request for pwr_pin failed!\n ");
			goto err;
		}

		gpio_direction_output(vga->en_pin, vga->en_val);
	}

	vga->lcdc_id = DISPLAY_SOURCE_LCDC0;
	
	ret = vga_get_screen_info(vga);
	if (ret < 0)
		goto err;
	vga_switch_screen(vga);
	
	printk("VGA probe successful\n");
	return 0;
err:
	vga_unregister_display_sysfs(vga);
	return ret;
	
}

static int vga_i2c_remove(struct i2c_client *client)
{
	return 0;
}

#if defined(CONFIG_OF)
static struct of_device_id vga_dt_ids[] = {
	{.compatible = "rockchip,vga" },
	{ }
};
#endif

static const struct i2c_device_id vga_id[] = {
	{ "vga_i2c", 0 },
	{ }
};

static struct i2c_driver vga_i2c_driver  = {
	.driver = {
		.name  = "vga_i2c",
		.owner = THIS_MODULE,
#if defined(CONFIG_OF)
		.of_match_table = of_match_ptr(vga_dt_ids),
#endif
	},
	.probe		= &vga_i2c_probe,
	.remove		= &vga_i2c_remove,
	.id_table	= vga_id,
};

module_i2c_driver(vga_i2c_driver);
