#
# Makefile for the touchscreen drivers.
#
# Each configuration option enables a list of files.


obj-$(CONFIG_ROCKCHIP_REMOTECTL_PWM)      += rockchip_pwm_remotectl.o
obj-$(CONFIG_ROCKCHIP_REMOTECTL_GPIO)      += rkxx_remotectl.o
